### ISSUE TITLE
ec2-user should not be created directly on the image

### ISSUE THREAD

**Issue by jsalatiel** [AlmaLinux/cloud-images#28]
Testing AlmaLinux release 8.4 (Electric Cheetah) AWS AMI Image, I noticed that I can not override the default ec2-user  by passing some cloud-init data on the ec2 launch webui.
It appears that the user is hardcoded in the image, instead of being created AFTER the ec2 first launch. 
I can see in the logs from one machine launched at 2021-07-22 that the ec2-user was actually created at 2021-05-31, which shows that it is hardcoded on the image.

```
2021-05-31 17:06:59,236 - subp.py[DEBUG]: Running hidden command to protect sensitive input/output logstring: ['useradd', 'ec2-user', '--comment', 'Cloud User', '--groups', 'adm,systemd-journal', '--shell', '/bin/bash', '-m']
```

The following user-data when used on redhat, centos7, amazonlinux and ubuntu will override the default user allowing me to use my own username on any ec2 linux flavour I want to.

```
#cloud-config
ssh_pwauth: 1
cloud_config_modules:
 - runcmd
cloud_final_modules:
- [users-groups,always]
users:
  - name: mycustomuser
    groups: [ wheel ]
    sudo: [ "ALL=(ALL) NOPASSWD:ALL" ]
    shell: /bin/bash
    lock_passwd: false
    expiredate: 2099-12-31
...
```

I was expecting the same behaviour on AlmaLinux, but since the ec2-user was previously created on the image, I will have the new ec2 instance with the ec2-user AND the one I have asked to create ( with uid 1001 ).

Would it be possible to replicate the same behaviour that exists on rhel, centos7 and amazonlinux ?
